# Generated by Django 3.2.12 on 2022-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('mainapp', '0005_productcategory_is_active'),
=======
        ("mainapp", "0005_productcategory_is_active"),
>>>>>>> f671007dcd137815c7eb1f2c4a76de74c2e8accb
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='продукт активен'),
=======
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="продукт активен"),
>>>>>>> f671007dcd137815c7eb1f2c4a76de74c2e8accb
        ),
    ]
