# Generated by Django 3.2.12 on 2022-04-24 04:27

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0005_create_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 26, 4, 27, 17, 242416, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
